### PR TITLE
Correlations info in analysis settings takes precedence over that in model settings

### PR DESCRIPTION
**Pull request by ncerutti**
### Correlations info in analysis settings takes precedence over that in model settings
The default model correlation factors can be overwritten by specific "correlation_settings" added to the analysis settings file.

Described in Issue #1088 (and related to Issue #910).

#### Notes:
Nothing will be done in case no model settings are present. Also note that only the correlation factors will be overwritten (i.e., the supported perils still must be set in the model settings).

### CODE REVIEW

**Review by johcarter — COMMENTED** [review]
Works perfectly, @ncerutti thank you! 

Although it would work exactly the same, I wonder whether the correct place for the correlation_settings would be nested in the model_settings{} blob within the analysis settings json file? Since specifying the correlation factors depends on what the peril correlation groups are, which are model specific and must also be specified in model_settings json.

**Comment by johcarter** [comment]
what do you think about the above question please @sstruzik ?

**Review by johcarter — APPROVED** [review]
Works as expected when analysis correlation settings are nested in model_settings blob in analysis settings json.

As long as peril correlation groups are defined by the modeller, analysis correlations setting are used to overwrite model correlation settings.  Model correlation_settings do not need to be defined (model settings json, correlation_settings{} blob present ) for analysis correlation settings to be applied.  I think this behaviour is fine.

**Comment by ncerutti** [comment]
> Works as expected when analysis correlation settings are nested in model_settings blob in analysis settings json.
> 
> As long as peril correlation groups are defined by the modeller, analysis correlations setting are used to overwrite model correlation settings. Model correlation_settings do not need to be defined (model settings json, correlation_settings{} blob present ) for analysis correlation settings to be applied. I think this behaviour is fine.

Thank you, @johcarter! If the need arises in the future, further adjusting the fields to overwrite and their sources should be straightforward.

**Review by sstruzik — APPROVED** [review]

**Pull request merged**
