### PR TITLE
 Storage Manager fixes for Platform Lot3

### PR DESCRIPTION
**Pull request by sambles**
### Storage Manager fixes for Platform Lot3
* Fixed run error `Fatal Python error: PyGILState_Release` when using remote storage, issue comes from `pyarrow==14.x.x` 
* Fixed unhelpful error message when storage manager credentials are invalid. If running with remote storage the method `model_storage.listdir()` is called to check the connection before continuing with the execution. 
* Fixed platform error, skip file copy of `model_storage_config_fp` if the file already exists and is the same.  

### Remaining Issues 
* Higher than expected memory usage when running a model from remote storage 
* Intermittent execution error ` invalid stream type: 0` when running a model with remote data.  

Needed for https://github.com/OasisLMF/OasisPlatform/pull/958

### CODE REVIEW

**Comment by sambles** [comment]
Error when running gulmc using S3 storage: 
```
2024-03-21 15:55:39,560 - oasislmf - INFO - {'alloc_rule': 1, 'debug': 0, 'file_in': None, 'file_out': None, 'loss_threshold': 0.0, 'sample_size': 5, 'effective_damageability': False, 'ignore_correlation': False, 'ignore_haz_correlation': False, 'ignore_f
2024-03-21 15:55:39,560 - oasislmf - INFO - starting process
2024-03-21 15:55:40,916 - py.warnings - WARNING - /home/sam/repos/venv/3py/lib/python3.11/site-packages/oasislmf/pytools/data_layer/oasis_files/correlations.py:120: UserWarning: loadtxt: input contained no data: "./input/correlations.csv"
  correlations = np.loadtxt(correlations_fname, dtype=Correlation, delimiter=",", skiprows=1, ndmin=1)

2024-03-21 15:55:54,509 - oasislmf - ERROR - mmap length is greater than file size
Traceback (most recent call last):
  File "/home/sam/repos/venv/3py/lib/python3.11/site-packages/oasislmf/pytools/utils.py", line 102, in wrapper
    retval = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/repos/venv/3py/lib/python3.11/site-packages/oasislmf/pytools/gulmc/manager.py", line 236, in run 
    vuln_array, _, _ = get_vulns(model_storage, run_dir, vuln_dict, num_intensity_bins, ignore_file_type)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/repos/venv/3py/lib/python3.11/site-packages/oasislmf/pytools/getmodel/manager.py", line 496, in get_vulns
    vulns_bin = np.memmap(f, dtype=Vulnerability, offset=4, mode='r')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/repos/venv/3py/lib/python3.11/site-packages/numpy/core/memmap.py", line 267, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: mmap length is greater than file size

```

**Comment by sambles** [comment]
called from inside worker --> can't seem to find the events file
```
2024-03-21 16:04:55,192 - oasislmf - DEBUG -     model_storage == <oasis_data_manager.filestore.backends.aws_s3.AwsS3Storage object at 0x7f96b5c01240>
2024-03-21 16:04:55,192 - oasislmf - DEBUG -     ri == False
  0%|                                                                                                    | 0/1 [00:00<?, ?it/s]
2024-03-21 16:04:56,029 - oasislmf - ERROR - Could not find events data file: ['events_p.bin', 'events_p.bin']
Traceback (most recent call last):
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/cli/root.py", line 42, in run
    return super(OasisBaseCommand, self).run(args=args)
  File "/home/worker/.local/lib/python3.10/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/worker/.local/lib/python3.10/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/worker/.local/lib/python3.10/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/cli/command.py", line 150, in action
    manager_method(**_kwargs)
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/utils/log.py", line 123, in wrapper
    result = func(*args, **kwargs)
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/manager.py", line 90, in interface
    return computation_cls(**kwargs).run()
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/computation/run/generate_losses.py", line 43, in run
    cmd[0](**cmd[1]).run()
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/computation/generate/losses.py", line 616, in run
    analysis_settings = GenerateLossesDir.run(self)
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/computation/generate/losses.py", line 325, in run
    prepare_run_inputs(analysis_settings, model_run_fp, model_storage, ri=ri)
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/utils/log.py", line 123, in wrapper
    result = func(*args, **kwargs)
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/execution/bin.py", line 388, in prepare_run_inputs
    _prepare_input_bin(run_dir, 'events', model_settings, model_storage, setting_key='event_set', ri=ri)
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/execution/bin.py", line 320, in _prepare_input_bin
    raise OasisException('Could not find {} data file: {}'.format(bin_name, targets))
oasis_data_manager.errors.OasisException: Could not find events data file: ['events_p.bin', 'events_p.bin']
```

**Comment by sambles** [comment]
** stderror.err** - ktools crash 
```                                                                                                                                                                                                                                                          
Fatal Python error: PyGILState_Release: auto-releasing thread-state, but no thread-state for this thread                                                                                                                                                                                    
Python runtime state: finalizing (tstate=0x0000000000a74a38)

./run_ktools.sh: line 757: 56966 Done                    eve 3 24
     56970 Aborted                 | gulmc --random-generator=1 --model-df-engine='oasis_data_manager.df_reader.reader.OasisPandasReader' --vuln-cache-size 200 -S5 -L0 -a1
     56975                       | tee /tmp/uvwWvMG6dW/fifo/gul_P3
     56980                       | fmpy -a2
     56984                       | tee /tmp/uvwWvMG6dW/fifo/il_P3
     56990                       | fmpy -a3 -n -p RI_1 > /tmp/uvwWvMG6dW/fifo/ri_P3
grep: warning: * at start of expression
grep: warning: * at start of expression
./run_ktools.sh: line 764: 57012 Done                    eve 10 24
     57014 Killed                  | gulmc --random-generator=1 --model-df-engine='oasis_data_manager.df_reader.reader.OasisPandasReader' --vuln-cache-size 200 -S5 -L0 -a1
     57017 Killed                  | tee /tmp/uvwWvMG6dW/fifo/gul_P10
     57020 Killed                  | fmpy -a2
     57023 Killed                  | tee /tmp/uvwWvMG6dW/fifo/il_P10
     57027 Killed                  | fmpy -a3 -n -p RI_1 > /tmp/uvwWvMG6dW/fifo/ri_P10
./run_ktools.sh: line 771: 57086 Done                    eve 17 24
     57088 Killed                  | gulmc --random-generator=1 --model-df-engine='oasis_data_manager.df_reader.reader.OasisPandasReader' --vuln-cache-size 200 -S5 -L0 -a1
     57092 Killed                  | tee /tmp/uvwWvMG6dW/fifo/gul_P17
     57094 Killed                  | fmpy -a2
     57097 Killed                  | tee /tmp/uvwWvMG6dW/fifo/il_P17
     57098 Killed                  | fmpy -a3 -n -p RI_1 > /tmp/uvwWvMG6dW/fifo/ri_P17
FATAL:: Not a summarycalc stream invalid stream type: 0
FATAL:: Not a summarycalc stream invalid stream type: 0
FATAL:: Not a summarycalc stream invalid stream type: 0

```

**Comment by sambles** [comment]
Pyarrow needs pinning to a version above `14.0.0` to fix `Fatal Python error: PyGILState_Release`
See: https://github.com/apache/arrow/issues/39503

**Review by benhayes21 — APPROVED** [review]

**Review by sstruzik — APPROVED** [review]

**Pull request merged**
