### PR TITLE
Feature/oasis lmf 608 gul fm load balancer

### PR DESCRIPTION
**Pull request by sstruzik**
#608

### CODE REVIEW

**Comment by sambles** [comment]
Issue with the `"full_correlation": True`  option from analysis_settings.json 

 ## Case 1: More GUL processes than FM

some of the `fifo/full_correlation/gul_P1` are not piped into fmcalc
```
( eve 1 8 | getmodel | gulcalc -S10 -L0 -j /tmp/k4jIPXltS1/fifo/full_correlation/gul_P1 -a1 -i - | tee /tmp/k4jIPXltS1/fifo/gul_P1 > /tmp/k4jIPXltS1/fifo/gul_lb_P1  ) 2>> log/stderror.err &
( eve 2 8 | getmodel | gulcalc -S10 -L0 -j /tmp/k4jIPXltS1/fifo/full_correlation/gul_P2 -a1 -i - | tee /tmp/k4jIPXltS1/fifo/gul_P2 > /tmp/k4jIPXltS1/fifo/gul_lb_P2  ) 2>> log/stderror.err &
( load_balancer -i /tmp/k4jIPXltS1/fifo/gul_lb_P1 /tmp/k4jIPXltS1/fifo/gul_lb_P2 -o /tmp/k4jIPXltS1/fifo/lb_il_P1 ) 2>> log/stderror.err &
( eve 3 8 | getmodel | gulcalc -S10 -L0 -j /tmp/k4jIPXltS1/fifo/full_correlation/gul_P3 -a1 -i - | tee /tmp/k4jIPXltS1/fifo/gul_P3 > /tmp/k4jIPXltS1/fifo/gul_lb_P3  ) 2>> log/stderror.err &
( eve 4 8 | getmodel | gulcalc -S10 -L0 -j /tmp/k4jIPXltS1/fifo/full_correlation/gul_P4 -a1 -i - | tee /tmp/k4jIPXltS1/fifo/gul_P4 > /tmp/k4jIPXltS1/fifo/gul_lb_P4  ) 2>> log/stderror.err &
( load_balancer -i /tmp/k4jIPXltS1/fifo/gul_lb_P3 /tmp/k4jIPXltS1/fifo/gul_lb_P4 -o /tmp/k4jIPXltS1/fifo/lb_il_P2 ) 2>> log/stderror.err &
( eve 5 8 | getmodel | gulcalc -S10 -L0 -j /tmp/k4jIPXltS1/fifo/full_correlation/gul_P5 -a1 -i - | tee /tmp/k4jIPXltS1/fifo/gul_P5 > /tmp/k4jIPXltS1/fifo/gul_lb_P5  ) 2>> log/stderror.err &
( eve 6 8 | getmodel | gulcalc -S10 -L0 -j /tmp/k4jIPXltS1/fifo/full_correlation/gul_P6 -a1 -i - | tee /tmp/k4jIPXltS1/fifo/gul_P6 > /tmp/k4jIPXltS1/fifo/gul_lb_P6  ) 2>> log/stderror.err &
( load_balancer -i /tmp/k4jIPXltS1/fifo/gul_lb_P5 /tmp/k4jIPXltS1/fifo/gul_lb_P6 -o /tmp/k4jIPXltS1/fifo/lb_il_P3 ) 2>> log/stderror.err &
( eve 7 8 | getmodel | gulcalc -S10 -L0 -j /tmp/k4jIPXltS1/fifo/full_correlation/gul_P7 -a1 -i - | tee /tmp/k4jIPXltS1/fifo/gul_P7 > /tmp/k4jIPXltS1/fifo/gul_lb_P7  ) 2>> log/stderror.err &
( eve 8 8 | getmodel | gulcalc -S10 -L0 -j /tmp/k4jIPXltS1/fifo/full_correlation/gul_P8 -a1 -i - | tee /tmp/k4jIPXltS1/fifo/gul_P8 > /tmp/k4jIPXltS1/fifo/gul_lb_P8  ) 2>> log/stderror.err &
( load_balancer -i /tmp/k4jIPXltS1/fifo/gul_lb_P7 /tmp/k4jIPXltS1/fifo/gul_lb_P8 -o /tmp/k4jIPXltS1/fifo/lb_il_P4 ) 2>> log/stderror.err &
( fmcalc -a2 < /tmp/k4jIPXltS1/fifo/lb_il_P1 | tee /tmp/k4jIPXltS1/fifo/il_P1 | fmcalc -a3 -n -p RI_1 > /tmp/k4jIPXltS1/fifo/ri_P1 ) 2>> log/stderror.err &
( fmcalc -a2 < /tmp/k4jIPXltS1/fifo/lb_il_P2 | tee /tmp/k4jIPXltS1/fifo/il_P2 | fmcalc -a3 -n -p RI_1 > /tmp/k4jIPXltS1/fifo/ri_P2 ) 2>> log/stderror.err &
( fmcalc -a2 < /tmp/k4jIPXltS1/fifo/lb_il_P3 | tee /tmp/k4jIPXltS1/fifo/il_P3 | fmcalc -a3 -n -p RI_1 > /tmp/k4jIPXltS1/fifo/ri_P3 ) 2>> log/stderror.err &
( fmcalc -a2 < /tmp/k4jIPXltS1/fifo/lb_il_P4 | tee /tmp/k4jIPXltS1/fifo/il_P4 | fmcalc -a3 -n -p RI_1 > /tmp/k4jIPXltS1/fifo/ri_P4 ) 2>> log/stderror.err &

wait $pid1 $pid2 $pid3 $pid4 $pid5 $pid6 $pid7 $pid8 $pid9 $pid10 $pid11 $pid12 $pid13 $pid14 $pid15 $pid16 $pid17 $pid18 $pid19 $pid20 $pid21 $pid22 $pid23 $pid24 $pid25 $pid26 $pid27 $pid28 $pid29 $pid30 $pid31 $pid32

# --- Do computes for fully correlated output ---

( fmcalc -a2 < /tmp/k4jIPXltS1/fifo/full_correlation/gul_P1 | tee /tmp/k4jIPXltS1/fifo/full_correlation/il_P1 | fmcalc -a3 -n -p RI_1 > /tmp/k4jIPXltS1/fifo/full_correlation/ri_P1 ) 2>> log/stderror.err & fcpid1=$!
( fmcalc -a2 < /tmp/k4jIPXltS1/fifo/full_correlation/gul_P2 | tee /tmp/k4jIPXltS1/fifo/full_correlation/il_P2 | fmcalc -a3 -n -p RI_1 > /tmp/k4jIPXltS1/fifo/full_correlation/ri_P2 ) 2>> log/stderror.err & fcpid2=$!
( fmcalc -a2 < /tmp/k4jIPXltS1/fifo/full_correlation/gul_P3 | tee /tmp/k4jIPXltS1/fifo/full_correlation/il_P3 | fmcalc -a3 -n -p RI_1 > /tmp/k4jIPXltS1/fifo/full_correlation/ri_P3 ) 2>> log/stderror.err & fcpid3=$!
( fmcalc -a2 < /tmp/k4jIPXltS1/fifo/full_correlation/gul_P4 | tee /tmp/k4jIPXltS1/fifo/full_correlation/il_P4 | fmcalc -a3 -n -p RI_1 > /tmp/k4jIPXltS1/fifo/full_correlation/ri_P4 ) 2>> log/stderror.err & fcpid4=$!

```


 ## Case 2: More FM processes than GUL
run_ktools.sh errors with:
```
KTOOLS_STDERR:
/home/sam/repos/models/piwind/runs/losses-20200817112425/run_ktools.sh: line 321: /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P5: No such file or directory
/home/sam/repos/models/piwind/runs/losses-20200817112425/run_ktools.sh: line 323: /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P7: No such file or directory
doit: Read error on input stream
/home/sam/repos/models/piwind/runs/losses-20200817112425/run_ktools.sh: line 322: /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P6: No such file or directory
/home/sam/repos/models/piwind/runs/losses-20200817112425/run_ktools.sh: line 324: /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P8: No such file or directory
doit: Read error on input stream
doit: Read error on input stream
doit: Read error on input stream
```

```
( eve 1 4 | getmodel | gulcalc -S10 -L0 -j /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P1 -a1 -i - | tee /tmp/Gn0Z0v9TeG/fifo/gul_P1 > /tmp/Gn0Z0v9TeG/fifo/gul_lb_P1  ) 2>> log/stderror.err &
( load_balancer -i /tmp/Gn0Z0v9TeG/fifo/gul_lb_P1 -o /tmp/Gn0Z0v9TeG/fifo/lb_il_P1 /tmp/Gn0Z0v9TeG/fifo/lb_il_P2 ) 2>> log/stderror.err &
( eve 2 4 | getmodel | gulcalc -S10 -L0 -j /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P2 -a1 -i - | tee /tmp/Gn0Z0v9TeG/fifo/gul_P2 > /tmp/Gn0Z0v9TeG/fifo/gul_lb_P2  ) 2>> log/stderror.err &
( load_balancer -i /tmp/Gn0Z0v9TeG/fifo/gul_lb_P2 -o /tmp/Gn0Z0v9TeG/fifo/lb_il_P3 /tmp/Gn0Z0v9TeG/fifo/lb_il_P4 ) 2>> log/stderror.err &
( eve 3 4 | getmodel | gulcalc -S10 -L0 -j /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P3 -a1 -i - | tee /tmp/Gn0Z0v9TeG/fifo/gul_P3 > /tmp/Gn0Z0v9TeG/fifo/gul_lb_P3  ) 2>> log/stderror.err &
( load_balancer -i /tmp/Gn0Z0v9TeG/fifo/gul_lb_P3 -o /tmp/Gn0Z0v9TeG/fifo/lb_il_P5 /tmp/Gn0Z0v9TeG/fifo/lb_il_P6 ) 2>> log/stderror.err &
( eve 4 4 | getmodel | gulcalc -S10 -L0 -j /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P4 -a1 -i - | tee /tmp/Gn0Z0v9TeG/fifo/gul_P4 > /tmp/Gn0Z0v9TeG/fifo/gul_lb_P4  ) 2>> log/stderror.err &
( load_balancer -i /tmp/Gn0Z0v9TeG/fifo/gul_lb_P4 -o /tmp/Gn0Z0v9TeG/fifo/lb_il_P7 /tmp/Gn0Z0v9TeG/fifo/lb_il_P8 ) 2>> log/stderror.err &
( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/lb_il_P1 | tee /tmp/Gn0Z0v9TeG/fifo/il_P1 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/ri_P1 ) 2>> log/stderror.err &
( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/lb_il_P2 | tee /tmp/Gn0Z0v9TeG/fifo/il_P2 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/ri_P2 ) 2>> log/stderror.err &
( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/lb_il_P3 | tee /tmp/Gn0Z0v9TeG/fifo/il_P3 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/ri_P3 ) 2>> log/stderror.err &
( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/lb_il_P4 | tee /tmp/Gn0Z0v9TeG/fifo/il_P4 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/ri_P4 ) 2>> log/stderror.err &
( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/lb_il_P5 | tee /tmp/Gn0Z0v9TeG/fifo/il_P5 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/ri_P5 ) 2>> log/stderror.err &
( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/lb_il_P6 | tee /tmp/Gn0Z0v9TeG/fifo/il_P6 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/ri_P6 ) 2>> log/stderror.err &
( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/lb_il_P7 | tee /tmp/Gn0Z0v9TeG/fifo/il_P7 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/ri_P7 ) 2>> log/stderror.err &
( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/lb_il_P8 | tee /tmp/Gn0Z0v9TeG/fifo/il_P8 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/ri_P8 ) 2>> log/stderror.err &

wait $pid1 $pid2 $pid3 $pid4 $pid5 $pid6 $pid7 $pid8 $pid9 $pid10 $pid11 $pid12 $pid13 $pid14 $pid15 $pid16 $pid17 $pid18 $pid19 $pid20 $pid21 $pid22 $pid23 $pid24 $pid25 $pid26 $pid27 $pid28 $pid29 $pid30 $pid31 $pid32 $pid33 $pid34 $pid35 $pid36 $pid37 $pid38 $pid39 $pid40

# --- Do computes for fully correlated output ---

( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P1 | tee /tmp/Gn0Z0v9TeG/fifo/full_correlation/il_P1 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/full_correlation/ri_P1 ) 2>> log/stderror.err & fcpid1=$!
( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P2 | tee /tmp/Gn0Z0v9TeG/fifo/full_correlation/il_P2 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/full_correlation/ri_P2 ) 2>> log/stderror.err & fcpid2=$!
( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P3 | tee /tmp/Gn0Z0v9TeG/fifo/full_correlation/il_P3 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/full_correlation/ri_P3 ) 2>> log/stderror.err & fcpid3=$!
( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P4 | tee /tmp/Gn0Z0v9TeG/fifo/full_correlation/il_P4 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/full_correlation/ri_P4 ) 2>> log/stderror.err & fcpid4=$!
( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P5 | tee /tmp/Gn0Z0v9TeG/fifo/full_correlation/il_P5 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/full_correlation/ri_P5 ) 2>> log/stderror.err & fcpid5=$!
( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P6 | tee /tmp/Gn0Z0v9TeG/fifo/full_correlation/il_P6 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/full_correlation/ri_P6 ) 2>> log/stderror.err & fcpid6=$!
( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P7 | tee /tmp/Gn0Z0v9TeG/fifo/full_correlation/il_P7 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/full_correlation/ri_P7 ) 2>> log/stderror.err & fcpid7=$!
( fmcalc -a2 < /tmp/Gn0Z0v9TeG/fifo/full_correlation/gul_P8 | tee /tmp/Gn0Z0v9TeG/fifo/full_correlation/il_P8 | fmcalc -a3 -n -p RI_1 > /tmp/Gn0Z0v9TeG/fifo/full_correlation/ri_P8 ) 2>> log/stderror.err & fcpid8=$!

```

**Review by sambles — APPROVED** [review]
Looks good

**Review by sambles — APPROVED** [review]
Merge + improvements look good

**Review by hchagani-oasislmf — APPROVED** [review]
Thanks for fixing the full correlation PID issue @sstruzik, `bash.py` looks good to me.

**Pull request merged**
