### PR TITLE
Improvements to error logging, debugging, test runner

### PR DESCRIPTION
**Pull request by DanielFEvans**
A number of small improvements that make debugging, testing, etc. a bit easier:
- When running in Verbose mode, full exception tracebacks are logged/printed to screen, rather than just the exception message.
- Now that OasisLMF is Python 3 only, use the `raise ... from ...` syntax.
- In the bash script generation, use `set -e` to ensure that failures in the bash script (either by the custom loss module or ktools) cause a CalledProcessError to be raised. This fixes the strange behaviour where error messages from those commands would appear in the output, but OasisLMF would claim the run completed successfully (#205)
- Add `{posargs}` to tox.ini, which allows arguments to be passed through to the test runner.

With the last change, one can now run a specific file with:
`tox -- tests/some_test_file.py`
Or even a specific test with:
`tox -- tests/some_test_file.py::TestClass::test_task`

### CODE REVIEW

**Comment by sr-murthy** [comment]
@DanielFEvans The changes to verbose logging and exceptions look OK, but note that in relation to testing, the real test runner is pytest, not tox, and it is already possible to run specific test modules, test classes or test cases, e.g.

    python3.6 -m pytest -sp no:flaky -v tests/utils/test_data.py -x
    python3.6 -m pytest -sp no:flaky -v tests/utils/test_data.py::TestGetDataframe -x
    python3.6 -m pytest -sp no:flaky -v tests/utils/test_data.py::TestGetDataframe::test_get_dataframe__no_src_fp_or_buf_or_data_provided__oasis_exception_is_raised

For local testing I use pytest, not tox. The CI calls tox, but for running the entire test suite - there is no need to run specific test modules or test classes in the CI jobs.

Given that we've now only targeting one Python version tox is less useful that it was originally, when there were three separate versions of Python we were targeting.

**Comment by DanielFEvans** [comment]
If pytest is now the recommended test runner, then no problem. The readme is a little confusing, as it currently suggests three different ways to run the tests, with `tox` being the first suggestion, hence why I had been using it.

**Comment by DanielFEvans** [comment]
Although all that the change to tox.ini does is to pass through any extra options to `pytest`; I'd be tempted to leave the change just so it's more flexible in general?

**Comment by sr-murthy** [comment]
Yes, it's OK. I was pointing out that pytest has always been the default test runner. Tox isn't really a test runner, it just uses pytest underneath.

**Pull request merged**
