### PR TITLE
Multi-peril exposure run

### PR DESCRIPTION
**Pull request by sambles**
PR for issue #575 

Added `-p <int>` or `--num-subperils <int>` to set the number of subperils returned by deterministic key generator

### Example  
 [example_keys_output.zip](https://github.com/OasisLMF/OasisLMF/files/5225604/example_keys_output.zip)
Running the command `oasislmf exposure run --num-subperils 2` with a three row location file generates the following:  

|LocID|PerilID|CoverageTypeID|AreaPerilID|VulnerabilityID|
|-----|-------|--------------|-----------|---------------|
|1    |1      |1             |1          |1              |
|1    |1      |2             |2          |2              |
|1    |1      |3             |3          |3              |
|1    |1      |4             |4          |4              |
|1    |2      |1             |5          |5              |
|1    |2      |2             |6          |6              |
|1    |2      |3             |7          |7              |
|1    |2      |4             |8          |8              |
|2    |1      |1             |9          |9              |
|2    |1      |2             |10         |10             |
|2    |1      |3             |11         |11             |
|2    |1      |4             |12         |12             |
|2    |2      |1             |13         |13             |
|2    |2      |2             |14         |14             |
|2    |2      |3             |15         |15             |
|2    |2      |4             |16         |16             |
|3    |1      |1             |17         |17             |
|3    |1      |2             |18         |18             |
|3    |1      |3             |19         |19             |
|3    |1      |4             |20         |20             |
|3    |2      |1             |21         |21             |
|3    |2      |2             |22         |22             |
|3    |2      |3             |23         |23             |
|3    |2      |4             |24         |24             |

### CODE REVIEW

**Comment by johcarter** [comment]
could you amend guls to include the extra items too please Sam? In order that the loss results don't change then the loss for the multi peril items will be the single peril loss divided by p.

**Comment by johcarter** [comment]
sorry i didnt notice this PR before now

**Comment by sambles** [comment]
@johcarter  Fix added 

## Example: 1 Sub peril 
`oasislmf exposure run --num-subperils 1`
```
+-------------+--------------+-------------+-------------+-------------+-----------+--------------------+--------------+------------+
|   output_id |   portnumber |   accnumber |   locnumber |   polnumber |   item_id |   coverage_type_id |     loss_gul |    loss_il |
|-------------+--------------+-------------+-------------+-------------+-----------+--------------------+--------------+------------|
|           1 |            1 |           1 |           1 |           1 |         1 |                  1 | 1,000,000.00 | 869,565.25 |
|           2 |            1 |           1 |           1 |           1 |         2 |                  2 |   100,000.00 |  86,956.52 |
|           3 |            1 |           1 |           1 |           1 |         3 |                  3 |    50,000.00 |  43,478.26 |
|           4 |            1 |           1 |           1 |           1 |         4 |                  4 |    20,000.00 |  18,000.00 |
+-------------+--------------+-------------+-------------+-------------+-----------+--------------------+--------------+------------+
```

## Example: 2 Sub perils
`oasislmf exposure run --num-subperils 2`

```
Losses (loss factor=100.00%; total gul=2,340,000; total il=1,018,000)
+-------------+--------------+-------------+-------------+-------------+--------------------+--------------+------------+
|   output_id |   portnumber |   accnumber |   locnumber |   polnumber |   coverage_type_id |     loss_gul |    loss_il |
|-------------+--------------+-------------+-------------+-------------+--------------------+--------------+------------|
|           1 |            1 |           1 |           1 |           1 |                  1 | 1,000,000.00 | 434,782.66 |
|           2 |            1 |           1 |           1 |           1 |                  1 | 1,000,000.00 | 434,782.66 |
|           3 |            1 |           1 |           1 |           1 |                  2 |   100,000.00 |  43,478.27 |
|           4 |            1 |           1 |           1 |           1 |                  2 |   100,000.00 |  43,478.27 |
|           5 |            1 |           1 |           1 |           1 |                  3 |    50,000.00 |  21,739.13 |
|           6 |            1 |           1 |           1 |           1 |                  3 |    50,000.00 |  21,739.13 |
|           7 |            1 |           1 |           1 |           1 |                  4 |    20,000.00 |   9,000.00 |
|           8 |            1 |           1 |           1 |           1 |                  4 |    20,000.00 |   9,000.00 |
+-------------+--------------+-------------+-------------+-------------+--------------------+--------------+------------+
```

**Comment by johcarter** [comment]
thanks. we just need to adjust the ground up losses so that the TIV is not exceeded and the gross losses come out the same as if there were a single peril, please. the way to do this is the gul for each item is loss factor * TIV / p

In the case of fm4 the gross loss comes out right because of the limits applied, but we can't rely on that in general.

Losses (loss factor=100.00%; total gul=1,170,000; total il=1,018,000)
+-------------+--------------+-------------+-------------+-------------+--------------------+--------------+------------+
|   output_id |   portnumber |   accnumber |   locnumber |   polnumber |   coverage_type_id |     loss_gul |    loss_il |
|-------------+--------------+-------------+-------------+-------------+--------------------+--------------+------------|
|           1 |            1 |           1 |           1 |           1 |                  1 |  500,000.00 | 434,782.66 |
|           2 |            1 |           1 |           1 |           1 |                  1 |  500,000.00 | 434,782.66 |
|           3 |            1 |           1 |           1 |           1 |                  2 |    50,000.00 |  43,478.27 |
|           4 |            1 |           1 |           1 |           1 |                  2 |    50,000.00 |  43,478.27 |
|           5 |            1 |           1 |           1 |           1 |                  3 |     25,000.00 |  21,739.13 |
|           6 |            1 |           1 |           1 |           1 |                  3 |     25,000.00 |  21,739.13 |
|           7 |            1 |           1 |           1 |           1 |                  4 |     10,000.00 |   9,000.00 |
|           8 |            1 |           1 |           1 |           1 |                  4 |    10,000.00 |   9,000.00 |
+-------------+--------------+-------------+-------------+-------------+--------------------+--------------+------------+

**Comment by sambles** [comment]
done. If you want to hook that into the fm test examples its need to read in the number of sub-perils from somewhere in the test dir. How should that look like? 

## Fix example (5 sub-perils)
```
+-------------+--------------+-------------+-------------+-------------+--------------------+------------+------------+
|   output_id |   portnumber |   accnumber |   locnumber |   polnumber |   coverage_type_id |   loss_gul |    loss_il |
|-------------+--------------+-------------+-------------+-------------+--------------------+------------+------------|
|           1 |            1 |           1 |           1 |           1 |                  1 | 200,000.00 | 173,913.08 |
|           2 |            1 |           1 |           1 |           1 |                  1 | 200,000.00 | 173,913.08 |
|           3 |            1 |           1 |           1 |           1 |                  1 | 200,000.00 | 173,913.08 |
|           4 |            1 |           1 |           1 |           1 |                  1 | 200,000.00 | 173,913.08 |
|           5 |            1 |           1 |           1 |           1 |                  1 | 200,000.00 | 173,913.08 |
|           6 |            1 |           1 |           1 |           1 |                  2 |  20,000.00 |  17,391.31 |
|           7 |            1 |           1 |           1 |           1 |                  2 |  20,000.00 |  17,391.31 |
|           8 |            1 |           1 |           1 |           1 |                  2 |  20,000.00 |  17,391.31 |
|           9 |            1 |           1 |           1 |           1 |                  2 |  20,000.00 |  17,391.31 |
|          10 |            1 |           1 |           1 |           1 |                  2 |  20,000.00 |  17,391.31 |
|          11 |            1 |           1 |           1 |           1 |                  3 |  10,000.00 |   8,695.65 |
|          12 |            1 |           1 |           1 |           1 |                  3 |  10,000.00 |   8,695.65 |
|          13 |            1 |           1 |           1 |           1 |                  3 |  10,000.00 |   8,695.65 |
|          14 |            1 |           1 |           1 |           1 |                  3 |  10,000.00 |   8,695.65 |
|          15 |            1 |           1 |           1 |           1 |                  3 |  10,000.00 |   8,695.65 |
|          16 |            1 |           1 |           1 |           1 |                  4 |   4,000.00 |   3,600.00 |
|          17 |            1 |           1 |           1 |           1 |                  4 |   4,000.00 |   3,600.00 |
|          18 |            1 |           1 |           1 |           1 |                  4 |   4,000.00 |   3,600.00 |
|          19 |            1 |           1 |           1 |           1 |                  4 |   4,000.00 |   3,600.00 |
|          20 |            1 |           1 |           1 |           1 |                  4 |   4,000.00 |   3,600.00 |

```

**Comment by johcarter** [comment]
looks good Sam, thanks. I don't have an example at present but can look into it.

**Comment by sambles** [comment]
Okey thanks Joh, merging in for now

**Pull request merged**
