### PR TITLE
Add .json configuration to the sphinx docs generation process 

### PR DESCRIPTION
**Pull request by ncerutti**
### oasislmf.json options now included in docs generated by sphinx

Solves #1258. When sphinx creates the documentation, now along with Installation, Building and Running Models, and API Reference, there is also an entry detailing the options that can be inserted in the oasislmf.json configuration file (Options for the JSON Configuration File).

### CODE REVIEW

**Comment by ncerutti** [comment]
Old output (pre-PR) can be seen at: https://oasislmf.github.io/OasisLMF/index.html

New output can be seen in https://github.com/OasisLMF/OasisLMF/actions/runs/8907250506/artifacts/1463327218 (`Options for the JSON Configuration File` section)


Only question is: should I delete the `example use` after each entry? I would, unless we expect some to be different, eventually.

**Comment by sambles** [comment]
The linked output asset expired, re-ran job and attaching here: 
[github-pages.zip](https://github.com/OasisLMF/OasisLMF/files/15197850/github-pages.zip)

**Comment by sambles** [comment]
> Only question is: should I delete the example use after each entry? I would, unless we expect some to be different, eventually. 

Yes I agree, its not all that useful, something like expected types would be better. 
`type=<function str2bool at 0x7f4f6194c180>`  --> expected type are ['True', 'False', 1, 0 .. etc]
`type=<class 'int'>`  -->  expected type Int

But I'm noticing many flags don't have a `type` set, (like the filepath stuff)

**Comment by sambles** [comment]
I think the **Default value** is not populated either (Wrong from the original example! so that one is on me) 

They all seem to be listed as `None`, this information must be somewhere, but maybe not added into `RunCmd().arg_parser._actions` ?

**Comment by ncerutti** [comment]
Here is the output:

[github-pages.zip](https://github.com/OasisLMF/OasisLMF/files/15414940/github-pages.zip)

**Review by sambles — APPROVED** [review]

**Review by benhayes21 — APPROVED** [review]

**Pull request merged**
